<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="wheel_weight"  value="2" />
    <xacro:property name="wheel_diameter"  value="0.271" />
    <xacro:property name="wheel_length"  value="0.100" />
    <xacro:macro name="wheel" params="
        name
        parent
        xyz
        rpy">

        <!-- Joint -->
        <joint name="${name}_joint" type="continuous">
            <parent link="${parent}"/>
            <child link="${name}_link"/>
            <origin xyz="${xyz}" rpy="${rpy}"/>
            <axis xyz="0 1 0"/>
        </joint>

        <!-- Link -->
        <link name="${name}_link">
            <visual>
                <origin xyz="${(wheel_diameter/2)-0.025} ${-(wheel_length/2)+0.01} ${-((wheel_diameter/2))+0.025}" rpy="0 0 ${pi/2}"/>
                <geometry>
                    <mesh filename="package://msd700_robot_description/ROS2/meshes/wheel.stl"
                            scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="White">
                    <color rgba="1 1 1 1.0"/>
                </material>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="${pi/2} ${pi/2} 0"/>
                <geometry>
                    <cylinder radius="${(wheel_diameter/2)}" length="${wheel_length}"/>
                </geometry>
            </collision>

            <inertial>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <mass value="${wheel_weight}"/>
                <inertia
                    ixx="${1/12*wheel_weight*(3*(wheel_diameter/2)*(wheel_diameter/2) + wheel_length * wheel_length)}" 
                    iyy="${1/12*wheel_weight*(3*(wheel_diameter/2)*(wheel_diameter/2) + wheel_length * wheel_length)}" 
                    izz="${wheel_weight/2*(wheel_diameter/2)*(wheel_diameter/2)}"
                    ixy="0" ixz="0" iyz="0"/>
            </inertial>
        </link>
    </xacro:macro>
</robot>
